config/routes.rb
Rails.application.routes.draw do
  root to: "sessions#new"
  get "hi" => "static_pages#root"

  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]
  resources :user_countries, only: [:destroy, :create]
  namespace :api, defaults: { format: :json } do
    get "show" => "views#show"
    get "leaders" => "views#leaders"
    get "map" => "views#map"
  end
end

app/models/continent.rb
class Continent < ActiveRecord::Base
  validates :name, presence: true

  has_many :countries
end

app/models/country.rb
class Country < ActiveRecord::Base
  validates :name, :continent, presence: true

  belongs_to :continent
  has_many :user_countries, dependent: :destroy
  has_many :users, through: :user_countries, source: :user, inverse_of: :countries

end

app/models/session.rb
class Session < ActiveRecord::Base
  validates :user_id, :session_token, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :email, :password_digest, :name, presence: true
  validates :email, uniqueness: true
  validates :password, confirmation: true
  validates :password, length: { minimum: 6, allow_nil: true }
  validate :confirmation_on_signup

  attr_reader :password

  has_many :user_countries
  has_many :sessions
  has_many :countries, through: :user_countries, source: :country

  def self.find_by_credentials(email, password)
    user = User.find_by(email: email)
    return nil unless user && user.valid_password?(password)
    user
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def valid_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  private
  def confirmation_on_signup
    if !self.persisted? && !self.password_confirmation.present?
      errors[:password_confirmation] << "can't be blank"
    end
  end

end

app/models/user_country.rb
class UserCountry < ActiveRecord::Base
  validates :user, :country_id, presence: true
  validates :user, uniqueness: { scope: :country_id, message: "Whoops!"}

  belongs_to :user
  belongs_to :country
end

app/controllers/api/views_controller.rb
class Api::ViewsController < ApplicationController
  def show
    @countries = Country.includes(:continent)
  end

  def map
    @visited = current_user.countries
  end

  def leaders
    @top = User.select("users.name, COUNT(user_countries.id) AS number")
      .joins(:user_countries).group("users.name")
      .order("COUNT(user_countries.id) DESC").limit(10)

    @africa = User.select("users.name, COUNT(user_countries.id) AS number")
      .where("countries.continent_id = 1").joins(user_countries: :country)
      .group("users.name").order("COUNT(user_countries.id) DESC").limit(10)

    @asia = User.select("users.name, COUNT(user_countries.id) AS number")
      .where("countries.continent_id = 6").joins(user_countries: :country)
      .group("users.name").order("COUNT(user_countries.id) DESC").limit(10)

    @europe = User.select("users.name, COUNT(user_countries.id) AS number")
      .where("countries.continent_id = 4").joins(user_countries: :country)
      .group("users.name").order("COUNT(user_countries.id) DESC").limit(10)

    @namerica = User.select("users.name, COUNT(user_countries.id) AS number")
      .where("countries.continent_id = 2").joins(user_countries: :country)
      .group("users.name").order("COUNT(user_countries.id) DESC").limit(10)

    @samerica = User.select("users.name, COUNT(user_countries.id) AS number")
      .where("countries.continent_id = 3").joins(user_countries: :country)
      .group("users.name").order("COUNT(user_countries.id) DESC").limit(10)

    @oceania = User.select("users.name, COUNT(user_countries.id) AS number")
      .where("countries.continent_id = 5").joins(user_countries: :country)
      .group("users.name").order("COUNT(user_countries.id) DESC").limit(10)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :signed_in?

  private
  def current_user
    @current_user ||= session[:session_token] ? User.find(Session.find_by_session_token(session[:session_token]).user_id) : nil
  end

  def signed_in?
    !!current_user
  end

  def sign_in(user)
    @current_user = user
    new_token = SecureRandom.urlsafe_base64(16)
    session[:session_token] = new_token
    Session.create(user_id: user.id, session_token: new_token)
  end

  def sign_out
    sess = Session.find_by_session_token(session[:session_token])
    sess.destroy
    session[:session_token] = nil
  end

  def require_signed_in!
    redirect_to new_session_url unless signed_in?
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by_credentials(
    params[:user][:email],
    params[:user][:password]
    )

    if user
      sign_in(user)
      redirect_to "/hi"
    else
      flash.now[:errors] = ["Invalid username and/or password"]
      render :new
    end
  end

  def destroy
    sign_out
    redirect_to new_session_url
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :require_signed_in!

  def root
  end
end

app/controllers/user_countries_controller.rb
class UserCountriesController < ApplicationController


  def create
    @user_country = current_user.user_countries.new(country_id: params[:country_id])
    if @user_country.save
      render json: {}
    else

      render json: {error: "Error processing request"}, status: 420
    end
  end

  def destroy
    @user_country = current_user.user_countries.find_by({country_id: params[:country_id]})
    @user_country.destroy
    render json: {}
  end



end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in(@user)
      redirect_to "/hi"
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @countries = Country.all
  end

  private
    def user_params
      params.require(:user).permit(:password, :email, :name, :password_confirmation)
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
  def auth_token_input
    "<input
    type=\"hidden\"
    name=\"authenticity_token\"
    value=\"#{ form_authenticity_token }\">".html_safe
  end
end

app/views/layouts/_errors.html.erb
<%= flash[:errors].join("<br>").html_safe if flash[:errors] %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TravelBucket</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="group">
    <a class="logo" href="/hi" >TravelBucket</a>
    <% if signed_in? %>
    <h6 class="name">Hi, <%= current_user.name %>!</h6>
    <%= button_to "Sign Out", session_url, :method => :delete %>
    <% else %>
    <ul>
      <li><%= link_to "Sign In", new_session_url %></li>
      <li><%= link_to "Sign Up", new_user_url %></li>

    </ul>
    <% end %>
  </header>
<%= yield %>

</body>
</html>

app/views/static_pages/root.html.erb
<title>TravelBucket</title>
<div ng-app='myApp'>

<div class="view-container">
    <div ng-view class="view-frame"></div>
</div>

</div>

app/views/users/new.html.erb
<section class="signback">

  <section class="group sign">

    <h2 class="signs">Sign Up</h2>



    <form class="signs" action="<%= users_url %>" method="post">
      <%= auth_token_input %>
      <%= render "layouts/errors" %>
      <label>
        Name
      </label>
      <input type="text" name="user[name]" value="">

      <label>
        Email
      </label>
      <input type="email" name="user[email]" value="">

      <label>
        Password
      </label>
      <input type="password" name="user[password]" value="">

      <label>
        Confirm Password
      </label>
      <input type="password" name="user[password_confirmation]" value="">

      <input class="button" type="submit" value="Sign Up">
    </form>
  </section>
</section>